# -*- coding: utf-8 -*-
"""binary search2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-cxtoTzbxm75TTbfivxVr61oRDD5e_U
"""

n = int(input())
array = list(map(int, input().split()))

answer = -1

def binary_search(array, start, end):
    if start > end:
        return None
    mid = (start + end) // 2
    if array[mid] == mid:
        return mid
    elif array[mid] > mid:
        return binary_search(array, start, mid-1)
    else:
        return binary_search(array, mid+1, end)

result = binary_search(array, 0, n-1)
if result == None:
    print(-1)
else:
    print(result)