# -*- coding: utf-8 -*-
"""binary search3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-cxtoTzbxm75TTbfivxVr61oRDD5e_U
"""
# LeetCode: 167. Two Sum II - Input Array Is Sorted 
# https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/

## input으로 정수가 담긴 list와 target 값이 들어오면
## list 내 두 정수의 합이 target이 되도록 해당하는 정수의 index를 반환

def twoSum(self, numbers, target):
	for k, v in enumerate(numbers):   # index와 value를 모두 사용하는 경우 enumerate()를 사용하는 게 편리
		left, right = k+1, len(numbers)-1
		expected = target - v
		# 이진 검색으로 나머지 값 판별
		while left <= right:
			mid = left + (right-left) // 2
			if numbers[mid] < expected:
				left = mid + 1
			elif numbers[mid] > expected:
				right = mid - 1
			else:
				return k+1, mid+1
