# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-cxtoTzbxm75TTbfivxVr61oRDD5e_U
"""

def binary_search(array, target, start, end):
		while start <= end:
				mid = (start + end) // 2
				if array[mid] == target:
						return mid
				elif array[mid] > target:
						end = mid - 1
				else:
						start = mid + 1
				return None