# -*- coding: utf-8 -*-
"""linear search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-cxtoTzbxm75TTbfivxVr61oRDD5e_U
"""

def sequential_search(n, target, array):
	for i in range(n):
		if array[i] == target:
			return i + 1
