# -*- coding: utf-8 -*-
"""binary search3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-cxtoTzbxm75TTbfivxVr61oRDD5e_U
"""

class Solution:
    def intersection(self, nums1: List[int], nums2: List[int]) -> List[int]:
        answer = []
        for i in set(nums1):
            if i in nums2:
                answer.append(i)
        return answer

class Solution:
    def intersection(self, nums1: List[int], nums2: List[int]) -> List[int]:
        return set(nums1) & set(nums2)