# -*- coding: utf-8 -*-
"""two pointer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-cxtoTzbxm75TTbfivxVr61oRDD5e_U
"""

def twoSum(self, numbers, target):
		left, right = 0, len(numbers)-1
		while not left == right:
				if numbers[left] + numbers[right] < target:
						left += 1
				elif numbers[left] + numbers[right] > target:
						right -= 1
				else:
						return left+1, right+1