# -*- coding: utf-8 -*-
"""Counting sorting

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXCo8Qc6mVlHD0ShtwFqjbyyNEWZ5lu2
"""

array = [7, 5, 9, 0, 3, 1, 6, 2, 9, 1, 4, 8, 0, 5, 2]
count = [0] * (max(array) + 1)   # count 초기치

for i in range(len(array)):
		count[array[i]] += 1   # 인덱스 수만큼 count 업데이트

for i in range(len(count)):
		for j in range(count[i]):
				print(i, end = ' ')   # 인덱스를 count만큼 출력