# -*- coding: utf-8 -*-
"""Insert sorting

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXCo8Qc6mVlHD0ShtwFqjbyyNEWZ5lu2
"""

array = [7, 5, 9, 0 ,3, 1, 6, 2, 4, 8]

for i in range(1, len(array)):   # 7이 아닌 5(두번째 인덱스)부터 시작
		for j in range(i, 0 , -1):   # 비교할 원소는 아래 if문을 만족하면 한 칸 앞으로 옮겨지므로 계속해서 같은 원소를 비교하는 것
				if array[j] < array[j-1]:
						array[j], array[j-1] = array[j-1], array[j]
				else:
						break   # 자기보다 작은 데이터를 만나면 그 위치에서 멈춤

print(array)