# -*- coding: utf-8 -*-
"""Put more than one piece of information in the list: tuple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXCo8Qc6mVlHD0ShtwFqjbyyNEWZ5lu2
"""

def solution(N, stages):
    answer = []
    length = len(stages)
    
    for i in range(1, N+1):
        count = stages.count(i)
        
        if length == 0:
            fail = 0
        else:
            fail = count / length
            
        answer.append((i, fail))
        length -= count
        
    answer = sorted(answer, key = lambda t: t[1], reverse = True)
    
    answer = [i[0] for i in answer]
    return answer