# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xB6lvJSYYwRRk_CjotLfTv8N-QcmaYFB
"""

# 링크: https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/

class Solution:
    def sortedArrayToBST(self, nums: List[int]) -> Optional[TreeNode]:
        if not nums:
            return None

        mid = len(nums)//2
        
        node = TreeNode(nums[mid])
        node.left = self.sortedArrayToBST(nums[:mid])   # if문 없이 바로 지정하면 됨
        node.right = self.sortedArrayToBST(nums[mid+1:])
        return node
